Pizza Website
gabk17/Formation-Gabriel pull request #7
Opened 2022-02-16 14:03 UTC by gabk17

2022-02-21 11:25 UTC, lapwil requested changes
OK vraiment pas mal, juste quelques changements mais ce sera bon, le client va avoir une demande bientôt sur ton board trello

2022-02-21 11:25 UTC, lapwil commented on pizza-website/src/App.js
> +import "./components/fontAwesome/index";
ok donc maintenant par convention, il faut mettre un bloc avec les imports venant de libs externes

puis un bloc avec tes imports locaux

2022-02-21 11:25 UTC, lapwil commented on pizza-website/src/assets/index.js
> +export const illustration3 = require('./sketchyPizza.png')
ok c'est bien d'avoir fait un index ici, pourquoi ne pas avoir utilisé les illustrations 1 et 2 ?

2022-02-21 11:25 UTC, lapwil commented on pizza-website/src/components/CardItem.js
> +    return (
en ES6, il faut savoir que quand tu ne fais qu'un return, tu peux directement mettre les parenthèses

```
const Toto = (item) => {
  return (<...>);
}
```

est équivalent à 

```
const Toto = (item) => (
  <...>
);
```


donc quand ta méthode ne fait rien à part le return, privilégies la deuxième syntaxe avec les parenthèses

2022-02-21 11:25 UTC, lapwil commented on pizza-website/src/components/Cart.js
> +      <Checkout />
tu n'as besoin de ce component que quand le cartCount est empty aussi, tu pourras regrouper les 3 lignes dans une seule condition du coup ici, du coup je voudrais que tu le fasse avec une ternaire 😄

2022-02-21 11:25 UTC, lapwil commented on pizza-website/src/components/Checkout.js
> +  let tva = 22.4;
comme la TVA est une constante, tu peux utiliser `const` ici

2022-02-21 11:25 UTC, lapwil commented on pizza-website/src/components/Home.js
> +        </Carousel>
chaud pour que tu fasses un component pour ce carousel, de plus tu pourras simplifier le code pour les items :) je te laisse chercher comment le faire

2022-02-21 11:25 UTC, lapwil commented on pizza-website/src/components/PizzaDetail.js
> +  const[cartBtn, setCartBtn] = useState("Add to Cart");
espace manquant après le `const`

2022-02-21 11:42 UTC, gabk17 commented on pizza-website/src/assets/index.js
> +export const illustration3 = require('./sketchyPizza.png')
je les avais utilisés une fois mais j’ai changé d’avis et utilisé d’autres photos

2022-02-21 13:12 UTC, lapwil approved these changes

2022-02-23 10:05 UTC, lapwil requested changes
niveau architecture:

quand tu fichier contient du JSX, il faut que ce soit un fichier `.jsx` du coup par convention

tout est rangé en vrac c'est pas simple de s'y retrouver. L'architecture devrait être:

- src
- - assets
- - components
- - containers
- - router
- - reducers
- - utils
- - store et autres fichiers genre index.js, etc

2022-02-23 10:05 UTC, lapwil commented on pizza-website/src/components/PizzaDetail.js
> +              </DropdownButton>
nope, je préfèrerai que tu mettes un bouton +, un bouton - et le compteur au milieu

2022-02-23 10:05 UTC, lapwil commented on pizza-website/src/components/Home.js
> +  }
ya un soucis dans la logique ici, au moment où la notif se dismiss faudrait pas qu'en partant et retournant sur la home on ait à nouveau la notif qui pop

2022-02-23 10:05 UTC, lapwil commented on pizza-website/src/components/redux/reducers/index.js
> +import orderReducer from "./orderReducer";
faut les virer ceux là

2022-02-23 10:05 UTC, lapwil commented on pizza-website/src/components/redux/reduxsauce/orderActionTypes.js
> +`);
pas besoin de ça, avec reduxsauce, on les déclare dans le fichier du reducer, ça permet de tout avoir au même endroit

2022-02-24 14:31 UTC, merged